//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPRWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPRDBEntities : DbContext
    {
        public OPRDBEntities()
            : base("name=OPRDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Path> Paths { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
