//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPRWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public string Note { get; set; }
        public string Addr { get; set; }
        public Nullable<int> StopOrder { get; set; }
        public Nullable<bool> Completed { get; set; }
        public System.Guid StopID { get; set; }
        public Nullable<System.Guid> PathID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual Path Path { get; set; }
    }
}
